name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Info
      run: |
        rustc --version
        cargo --version

    - name: Build
      run: cargo build

    - name: Format
      run: cargo fmt --check

    - name: Lint
      run: cargo clippy

    - name: Run tests
      run: cargo test
